### ISSUE TITLE
How to record a video with AR camera in Unity ? 

### ISSUE THREAD

**Issue by Andy23kira** [Everyplay/everyplay-unity-sdk#18]
Hello everyone, I wanna know how to record a video with  AR camera Vuforia Unity, I found some codes but I also don't know how to use it, please someone can helps me?? 
Please please, Help me, Help me

**Comment by ullatussimo** [comment]
Hello,

Were you able to set up recording with Vuforia?
I tested the recording with Vuforia once and, apart from audio, recording worked fine.
Unfortunately Vuforia uses MediaPlayer to play the streamed audio, which our SDK can not properly capture at the moment.

However, if you use Vuforia's AR camera feature and play the audio through Unity, everything should work ok.

Basically, set up the Vuforia functionality as you want, integrate our SDK, set up your client_id & secret in Unity->Edit->Everyplay Settings and enable the platform(s) you want to use Everyplay on.

After this, you just need to call Everyplay.StartRecording when you want to start a recording session and Everyplay.StopRecording when you want to stop it. You can then play back the recorded video by calling Everyplay.PlayLastRecording or bring up the share modal by calling Everyplay.ShowSharingModal.

I highly recommend checking recording support with Everyplay.IsRecordingSupported && Everyplay.IsReadyForRecording before starting the recording session in order to make sure that a session can be recorded.

Hope this helps.

Cheers,
Simo

**Comment by Neogene** [comment]
Sadly Everyplay is deprecated.

**Comment by voxelbustersold** [comment]
We have a plugin on Asset Store which can record AR Sessions. Please have a look at [Cross Platform Replay Kit](http://u3d.as/1nN3)
