### ISSUE TITLE
Crash/Slow on Samsung Devices

### ISSUE THREAD

**Issue by flyingmate** [Everyplay/everyplay-unity-sdk#5]
Is it possible to check if everyplay recording is slowing down game framerates? Recording makes Samsung devices like Galaxy 3/4 so slow, even crashed. Those devices have more than one core so singlecore check method in Everyplay SDK is not useful. Thank you in advance.

**Comment by aet** [comment]
The framerate usually jumps and up down with typical Android devices even because of the power management stuff, so that's pretty hard to predict.. there's game specific black listing functionality available at the developers site.

For any crash logs with ADB logcat history/potential test case, please send them to our support, thanks!
